package tocook.dao.generator;

import tocook.dto.generator.CommonMst;

public interface CommonMstMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table common_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int deleteByPrimaryKey(String commonId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table common_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insert(CommonMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table common_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insertSelective(CommonMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table common_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    CommonMst selectByPrimaryKey(String commonId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table common_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKeySelective(CommonMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table common_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKey(CommonMst record);
}