package tocook.dao.generator;

import tocook.dto.generator.CookUserMst;

public interface CookUserMstMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_user_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_user_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insert(CookUserMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_user_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insertSelective(CookUserMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_user_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    CookUserMst selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_user_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKeySelective(CookUserMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_user_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKey(CookUserMst record);
}