package tocook.dao.generator;

import tocook.dto.generator.CookMst;

public interface CookMstMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int deleteByPrimaryKey(String cookId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insert(CookMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insertSelective(CookMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    CookMst selectByPrimaryKey(String cookId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKeySelective(CookMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table cook_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKey(CookMst record);
}