package tocook.dao.generator;

import tocook.dto.generator.FoodMst;

public interface FoodMstMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table food_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int deleteByPrimaryKey(String foodId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table food_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insert(FoodMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table food_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insertSelective(FoodMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table food_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    FoodMst selectByPrimaryKey(String foodId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table food_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKeySelective(FoodMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table food_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKey(FoodMst record);
}