package tocook.dao.generator;

import tocook.dto.generator.RoutineMst;

public interface RoutineMstMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int deleteByPrimaryKey(String routineId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insert(RoutineMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insertSelective(RoutineMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    RoutineMst selectByPrimaryKey(String routineId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKeySelective(RoutineMst record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_mst
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKey(RoutineMst record);
}