package tocook.dao.generator;

import tocook.dto.generator.RoutineEatTbl;

public interface RoutineEatTblMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_eat_tbl
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int deleteByPrimaryKey(String routineEatId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_eat_tbl
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insert(RoutineEatTbl record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_eat_tbl
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int insertSelective(RoutineEatTbl record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_eat_tbl
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    RoutineEatTbl selectByPrimaryKey(String routineEatId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_eat_tbl
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKeySelective(RoutineEatTbl record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table routine_eat_tbl
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    int updateByPrimaryKey(RoutineEatTbl record);
}