package tocook.dto.generator;

import java.util.Date;

public class CookMst {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cook_mst.cook_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String cookId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cook_mst.cook_name
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String cookName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cook_mst.cook_process
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String cookProcess;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cook_mst.cook_price
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Long cookPrice;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cook_mst.cook_movie
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String cookMovie;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cook_mst.cook_url
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String cookUrl;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cook_mst.cook_flg
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Boolean cookFlg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cook_mst.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cook_mst.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Date updateDatetime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column cook_mst.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Short version;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cook_mst.cook_id
     * @return  the value of cook_mst.cook_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getCookId() {
        return cookId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cook_mst.cook_id
     * @param cookId  the value for cook_mst.cook_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setCookId(String cookId) {
        this.cookId = cookId == null ? null : cookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cook_mst.cook_name
     * @return  the value of cook_mst.cook_name
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getCookName() {
        return cookName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cook_mst.cook_name
     * @param cookName  the value for cook_mst.cook_name
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setCookName(String cookName) {
        this.cookName = cookName == null ? null : cookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cook_mst.cook_process
     * @return  the value of cook_mst.cook_process
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getCookProcess() {
        return cookProcess;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cook_mst.cook_process
     * @param cookProcess  the value for cook_mst.cook_process
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setCookProcess(String cookProcess) {
        this.cookProcess = cookProcess == null ? null : cookProcess.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cook_mst.cook_price
     * @return  the value of cook_mst.cook_price
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Long getCookPrice() {
        return cookPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cook_mst.cook_price
     * @param cookPrice  the value for cook_mst.cook_price
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setCookPrice(Long cookPrice) {
        this.cookPrice = cookPrice;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cook_mst.cook_movie
     * @return  the value of cook_mst.cook_movie
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getCookMovie() {
        return cookMovie;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cook_mst.cook_movie
     * @param cookMovie  the value for cook_mst.cook_movie
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setCookMovie(String cookMovie) {
        this.cookMovie = cookMovie == null ? null : cookMovie.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cook_mst.cook_url
     * @return  the value of cook_mst.cook_url
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getCookUrl() {
        return cookUrl;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cook_mst.cook_url
     * @param cookUrl  the value for cook_mst.cook_url
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setCookUrl(String cookUrl) {
        this.cookUrl = cookUrl == null ? null : cookUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cook_mst.cook_flg
     * @return  the value of cook_mst.cook_flg
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Boolean getCookFlg() {
        return cookFlg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cook_mst.cook_flg
     * @param cookFlg  the value for cook_mst.cook_flg
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setCookFlg(Boolean cookFlg) {
        this.cookFlg = cookFlg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cook_mst.user_id
     * @return  the value of cook_mst.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cook_mst.user_id
     * @param userId  the value for cook_mst.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cook_mst.update_datetime
     * @return  the value of cook_mst.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cook_mst.update_datetime
     * @param updateDatetime  the value for cook_mst.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column cook_mst.version
     * @return  the value of cook_mst.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Short getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column cook_mst.version
     * @param version  the value for cook_mst.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setVersion(Short version) {
        this.version = version;
    }
}