package tocook.dto.generator;

import java.util.Date;

public class FoodMst {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.food_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String foodId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.food_name
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String foodName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.food_unit
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String foodUnit;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.others1
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String others1;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.others2
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String others2;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.others3
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String others3;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.others4
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String others4;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.others5
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String others5;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Date updateDatetime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column food_mst.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Short version;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.food_id
     * @return  the value of food_mst.food_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.food_id
     * @param foodId  the value for food_mst.food_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setFoodId(String foodId) {
        this.foodId = foodId == null ? null : foodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.food_name
     * @return  the value of food_mst.food_name
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getFoodName() {
        return foodName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.food_name
     * @param foodName  the value for food_mst.food_name
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setFoodName(String foodName) {
        this.foodName = foodName == null ? null : foodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.food_unit
     * @return  the value of food_mst.food_unit
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getFoodUnit() {
        return foodUnit;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.food_unit
     * @param foodUnit  the value for food_mst.food_unit
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setFoodUnit(String foodUnit) {
        this.foodUnit = foodUnit == null ? null : foodUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.others1
     * @return  the value of food_mst.others1
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getOthers1() {
        return others1;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.others1
     * @param others1  the value for food_mst.others1
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setOthers1(String others1) {
        this.others1 = others1 == null ? null : others1.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.others2
     * @return  the value of food_mst.others2
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getOthers2() {
        return others2;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.others2
     * @param others2  the value for food_mst.others2
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setOthers2(String others2) {
        this.others2 = others2 == null ? null : others2.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.others3
     * @return  the value of food_mst.others3
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getOthers3() {
        return others3;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.others3
     * @param others3  the value for food_mst.others3
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setOthers3(String others3) {
        this.others3 = others3 == null ? null : others3.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.others4
     * @return  the value of food_mst.others4
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getOthers4() {
        return others4;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.others4
     * @param others4  the value for food_mst.others4
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setOthers4(String others4) {
        this.others4 = others4 == null ? null : others4.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.others5
     * @return  the value of food_mst.others5
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getOthers5() {
        return others5;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.others5
     * @param others5  the value for food_mst.others5
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setOthers5(String others5) {
        this.others5 = others5 == null ? null : others5.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.user_id
     * @return  the value of food_mst.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.user_id
     * @param userId  the value for food_mst.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.update_datetime
     * @return  the value of food_mst.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.update_datetime
     * @param updateDatetime  the value for food_mst.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column food_mst.version
     * @return  the value of food_mst.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Short getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column food_mst.version
     * @param version  the value for food_mst.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setVersion(Short version) {
        this.version = version;
    }
}