package tocook.dto.generator;

import java.util.Date;

public class RoutineMst {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_mst.routine_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String routineId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_mst.routine_name
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String routineName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_mst.routine_maxday
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Short routineMaxday;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_mst.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_mst.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Date updateDatetime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_mst.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Short version;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_mst.routine_id
     * @return  the value of routine_mst.routine_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getRoutineId() {
        return routineId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_mst.routine_id
     * @param routineId  the value for routine_mst.routine_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setRoutineId(String routineId) {
        this.routineId = routineId == null ? null : routineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_mst.routine_name
     * @return  the value of routine_mst.routine_name
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getRoutineName() {
        return routineName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_mst.routine_name
     * @param routineName  the value for routine_mst.routine_name
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setRoutineName(String routineName) {
        this.routineName = routineName == null ? null : routineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_mst.routine_maxday
     * @return  the value of routine_mst.routine_maxday
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Short getRoutineMaxday() {
        return routineMaxday;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_mst.routine_maxday
     * @param routineMaxday  the value for routine_mst.routine_maxday
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setRoutineMaxday(Short routineMaxday) {
        this.routineMaxday = routineMaxday;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_mst.user_id
     * @return  the value of routine_mst.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_mst.user_id
     * @param userId  the value for routine_mst.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_mst.update_datetime
     * @return  the value of routine_mst.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_mst.update_datetime
     * @param updateDatetime  the value for routine_mst.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_mst.version
     * @return  the value of routine_mst.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Short getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_mst.version
     * @param version  the value for routine_mst.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setVersion(Short version) {
        this.version = version;
    }
}