package tocook.dto.generator;

import java.util.Date;

public class RoutineEatTbl {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_eat_tbl.routine_eat_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String routineEatId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_eat_tbl.routine_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String routineId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_eat_tbl.cook_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String cookId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_eat_tbl.routine_day
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Short routineDay;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_eat_tbl.routine_time
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Short routineTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_eat_tbl.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_eat_tbl.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Date updateDatetime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column routine_eat_tbl.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Short version;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_eat_tbl.routine_eat_id
     * @return  the value of routine_eat_tbl.routine_eat_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getRoutineEatId() {
        return routineEatId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_eat_tbl.routine_eat_id
     * @param routineEatId  the value for routine_eat_tbl.routine_eat_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setRoutineEatId(String routineEatId) {
        this.routineEatId = routineEatId == null ? null : routineEatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_eat_tbl.routine_id
     * @return  the value of routine_eat_tbl.routine_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getRoutineId() {
        return routineId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_eat_tbl.routine_id
     * @param routineId  the value for routine_eat_tbl.routine_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setRoutineId(String routineId) {
        this.routineId = routineId == null ? null : routineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_eat_tbl.cook_id
     * @return  the value of routine_eat_tbl.cook_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getCookId() {
        return cookId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_eat_tbl.cook_id
     * @param cookId  the value for routine_eat_tbl.cook_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setCookId(String cookId) {
        this.cookId = cookId == null ? null : cookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_eat_tbl.routine_day
     * @return  the value of routine_eat_tbl.routine_day
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Short getRoutineDay() {
        return routineDay;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_eat_tbl.routine_day
     * @param routineDay  the value for routine_eat_tbl.routine_day
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setRoutineDay(Short routineDay) {
        this.routineDay = routineDay;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_eat_tbl.routine_time
     * @return  the value of routine_eat_tbl.routine_time
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Short getRoutineTime() {
        return routineTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_eat_tbl.routine_time
     * @param routineTime  the value for routine_eat_tbl.routine_time
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setRoutineTime(Short routineTime) {
        this.routineTime = routineTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_eat_tbl.user_id
     * @return  the value of routine_eat_tbl.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_eat_tbl.user_id
     * @param userId  the value for routine_eat_tbl.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_eat_tbl.update_datetime
     * @return  the value of routine_eat_tbl.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_eat_tbl.update_datetime
     * @param updateDatetime  the value for routine_eat_tbl.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column routine_eat_tbl.version
     * @return  the value of routine_eat_tbl.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Short getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column routine_eat_tbl.version
     * @param version  the value for routine_eat_tbl.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setVersion(Short version) {
        this.version = version;
    }
}