package tocook.dto.generator;

import java.util.Date;

public class ScheduleTbl {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_tbl.schedule_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String scheduleId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_tbl.schedule_date
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Date scheduleDate;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_tbl.schedule_time
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Short scheduleTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_tbl.cook_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String cookId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_tbl.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private String userId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_tbl.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Date updateDatetime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column schedule_tbl.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    private Short version;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_tbl.schedule_id
     * @return  the value of schedule_tbl.schedule_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getScheduleId() {
        return scheduleId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_tbl.schedule_id
     * @param scheduleId  the value for schedule_tbl.schedule_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setScheduleId(String scheduleId) {
        this.scheduleId = scheduleId == null ? null : scheduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_tbl.schedule_date
     * @return  the value of schedule_tbl.schedule_date
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Date getScheduleDate() {
        return scheduleDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_tbl.schedule_date
     * @param scheduleDate  the value for schedule_tbl.schedule_date
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setScheduleDate(Date scheduleDate) {
        this.scheduleDate = scheduleDate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_tbl.schedule_time
     * @return  the value of schedule_tbl.schedule_time
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Short getScheduleTime() {
        return scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_tbl.schedule_time
     * @param scheduleTime  the value for schedule_tbl.schedule_time
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setScheduleTime(Short scheduleTime) {
        this.scheduleTime = scheduleTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_tbl.cook_id
     * @return  the value of schedule_tbl.cook_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getCookId() {
        return cookId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_tbl.cook_id
     * @param cookId  the value for schedule_tbl.cook_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setCookId(String cookId) {
        this.cookId = cookId == null ? null : cookId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_tbl.user_id
     * @return  the value of schedule_tbl.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_tbl.user_id
     * @param userId  the value for schedule_tbl.user_id
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_tbl.update_datetime
     * @return  the value of schedule_tbl.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_tbl.update_datetime
     * @param updateDatetime  the value for schedule_tbl.update_datetime
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column schedule_tbl.version
     * @return  the value of schedule_tbl.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public Short getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column schedule_tbl.version
     * @param version  the value for schedule_tbl.version
     * @mbg.generated  Tue Jun 14 08:53:12 JST 2022
     */
    public void setVersion(Short version) {
        this.version = version;
    }
}